services:
  trustforge-be:
    image: trustforge-be:v1.0
    container_name: trustforge-be
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - SUPABASE_URL=http://192.168.1.149:8000
      - SUPABASE_ANON_KEY=
      - SUPABASE_SERVICE_KEY=
      - MOBSF_API_KEY=
      - MOBSF_API_URL=http://192.168.1.149:9005
      - REDIS_HOST=192.168.1.149
      - REDIS_PORT=6379
      - APP_PORT=3001
      - NODE_ENV=development
      - VIRUSTOTAL_API_KEY=
      - METADEFENDER_API_KEY=
      - HYBRID_ANALYSIS_API_KEY=
